### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by tomitrescak** [CroakyJejunoileitis/Sound-Localization-using-Microphone-Array-Beamforming#1]
Hi, I am interested in your approach, but I do not even know where to start ;)
We have an array of three microphones and we need to detect a position of a speaker.
At this moment we want to start simple and just point towards the source of the sound.
Would your method work? Is it possible to do this in real time?

**Comment by ChaitanyaKher** [comment]
Hi tomitrescak, sorry for the late reply, yes this code works, but can you elaborate more on what you want to do with the kind of hardware you have and the distance at which your source is going to be., additionally I can help you with the material I have.
